### ISSUE TITLE
usbip Error (WSL 2)

### ISSUE THREAD

**Issue by ghost** [rpasek/usbip-wsl2-instructions#8]
I am running WSL 2 with Ubuntu 20.04. Kernel version is 4.19.84-microsoft-standard. 
I have followed your instructions and everything goes well except this step:

**Copy USBIP tools libraries to location that USBIP tools can get to them**
it said there's no such file called **libsrc/.libs/libusbip.so.0**

inside that folder i found no such file by that name.

So I am getting error while trying to bind device attached to Windows machine.

> WARNING: usbip not found for kernel 4.19.84-microsoft

what to do now? is it due to kernel version or anything?

**Comment by pagkly** [comment]
Hi @thedozo I have the same kernel as yours but running ubuntu 18.04 from Microsoft store.
have you tried `apt install usbip` ?

**Comment by ghost** [comment]
> Hi @thedozo I have the same kernel as yours but running ubuntu 18.04 from Microsoft store.
> have you tried `apt install usbip` ?

Problem sovled after using Kernel 5.4.22.
